version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "file:/app/prisma/dev.db"
      NEXTAUTH_SECRET: "devsecret"
    volumes:
      - sqlite-data:/app/prisma
volumes:
  sqlite-data: {}
